// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SortItOut.DataAccess.Csc.Models
{
    public partial class AccountType
    {
        public AccountType()
        {
            Account = new HashSet<Account>();
        }

        public int AccountTypeId { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }

        public virtual ICollection<Account> Account { get; set; }
    }
}