// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SortItOut.DataAccess.Csc.Models
{
    public partial class Account
    {
        public int AccountId { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string PasswordHash { get; set; }
        public int? AccountTypeId { get; set; }

        public virtual AccountType AccountType { get; set; }
    }
}